server:
  port: 8080
  

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: testLatticeApp
  data:
    mongodb:
      authentication-database: admin
      host: 52.188.176.121
      port: 27017
      #username: root
      #password: example
      database: seguridad

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true